### PR TITLE
feat: added support for linked links in diffs

### PR DESCRIPTION
**Pull request by sohomdatta1**
Added support for HTML clickable "links" for the articles/images being pointed to in a Wikitext link

Bug: #220

Created a naive regex that detects wikilinks and adds a link to the article name part of the wikilink.

### CODE REVIEW

**Comment by sohomdatta1** [comment]
https://regex101.com/r/QwzU8z/3 (to test the regex)

**Comment by xinbenlv** [comment]
Thank you @sohomatta1, I will deploy a demo t see

**Comment by xinbenlv** [comment]
That is awesome! Tested and it works great

**Comment by xinbenlv** [comment]
Hi Sohom, thank you for this contribution. It turns out because the `parse` interface of MediaWiki is too slow, sometimes taking 30s - 60s to respond, it needs some additional logic to make it more lazy-load based. I am developing such features. And I currently temp unlaunch this feature, and will get them back when the lazy-loading method is done. Stay-tuned.

See #359

**Comment by sohomdatta1** [comment]
> @sohomdatta1
> 
> Hi Sohom, thank you for this contribution. It turns out because the `parse` interface of MediaWiki is too slow, sometimes taking 30s - 60s to respond, it needs some additional logic to make it more lazy-load based. I am developing such features. And I currently temp unlaunch this feature, and will get them back when the lazy-loading method is done. Stay-tuned.
> 
> See #359

Sure, that sound really cool :smile:

**Pull request merged**
